apiVersion: v1
kind: Service # https://kubernetes.io/docs/concepts/services-networking/service/
metadata:
  name: api-service
  namespace: default
spec:
  selector:
    app: synergychat-api
  ports:
  - name: api-port
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
---

