apiVersion: v1
kind: ConfigMap # https://kubernetes.io/docs/concepts/configuration/configmap/
metadata:
  name: synergychat-api-configmap
  namespace: default
data:
  API_PORT: "8080"
  API_DB_FILEPATH: /persist/db.json
  CRAWLER_BASE_URL: http://crawler-service.crawler.svc.cluster.local

