apiVersion: v1
kind: Service # https://kubernetes.io/docs/concepts/services-networking/service/
metadata:
  name: crawler-service
  namespace: crawler
spec:
  selector:
    app: synergychat-crawler
  ports:
  - name: crawler-port
    protocol: TCP
    port: 80
    targetPort: 8080
---
