apiVersion: v1
kind: Service # https://kubernetes.io/docs/concepts/services-networking/service/
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: synergychat-web
  ports:
  - name: service-port 
    protocol: TCP
    port: 80
    targetPort: 8080
---

